spring.application.name=budgeting
server.port=8080

# Pega todas as entities e cria as tabelas no banco de dados
#spring.jpa.hibernate.ddl-auto=create

# Pega todas as entities e atualiza as tabelas no banco de dados
spring.jpa.hibernate.ddl-auto=create

# Mostra os SQLs no console
spring.jpa.show-sql=true

# API Key
#dummy-key-para-testes: garante que o Spring Boot inicialize o contexto sem reclamar que a chave está nula durante o carregamento dos Beans.
#spring.ai.openai.api-key=${OPENAI_API_KEY:dummy-key-para-testes}

# GROQ
spring.ai.openai.api-key=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
spring.ai.openai.chat.api-key=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

# Base URL obrigatória para redirecionar o Spring Boot para a Groq
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.base-url=https://api.groq.com/openai


# Modelo (se for usar Groq, use openai/gpt-oss-20b; se for OpenAI, use gpt-4o-mini)
#spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.model=openai/gpt-oss-20b

#spring.ai.openai.chat.options.temperature=0.8
spring.ai.openai.chat.options.temperature=0.7

spring.ai.openai.chat.options.response-format-type=TEXT

spring.ai.model.audio.transcription=openai

# Modelo de transcrição de áudio
spring.ai.openai.audio.transcription.options.model=gpt-4o-mini-tts

# Linguagem
spring.ai.openai.audio.transcription.options.language=pt

# Formato de resposta
spring.ai.openai.audio.transcription.options.response-format=TEXT

# Para que tenha um pouco mais de contexto
spring.ai.openai.audio.transcription.options.prompt=Áudio em português brasileiro. \
  Áudio contém descrições de gastos financeiros. \
  As frases geralmente contém: \
    - um valor em reais (número + "reais"); \
    - uma ação (gastei, paguei, comprei); \
    - um local ou estabelecimento (mercado, farmácia, restaurante, loja, etc.).

# Quando instanciar um Speech, use o OpenAI como provedor de transcrição de áudio
spring.ai.model.audio.speech=openai

# Modelo de transcrição de áudio (se for usar Groq, use whisper-large-v3; se for OpenAI, use gpt-4o-mini-tts)
spring.ai.openai.audio.speech.options.model=whisper-large-v3

# Linguagem
spring.ai.openai.audio.speech.options.voice=nova

# Velocidade
spring.ai.openai.audio.speech.options.speed=1.2

# Formato de saída
spring.ai.openai.audio.speech.options.response-format=mp3

# Crie nada diferente do audio que esta passando
spring.ai.openai.audio.transcription.options.temperature=0

# Mostra os logs do Spring AI
logging.level.org.springframework.ai=DEBUG