# Subir um banco de dados usando Docker

services:

# Nome do serviço
  database:

# Imagem do container
    image: mysql:9.6

# Variáveis de ambiente
    environment:
      MYSQL_DATABASE: transactions
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3307:3306"
    volumes:
      - transaction_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uapp", "-papp"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  transaction_data:
